apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: ljkw9z7yb-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-java-springboot:3fd153d9f2cb82764efd60b3eae791289fe11c40@sha256:1ccdf1e8a6b9adf9f06a5865cf6e2ed97f200ddb8616861013a7e511b02468ee
          name: container-image
